CREATE TABLE CONSULTAS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    preco DECIMAL(10,2) NOT NULL,
    atendimento VARCHAR(100) NOT NULL,
    id_medico BIGINT NOT NULL,
    id_cliente BIGINT NOT NULL,
    data_consulta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MEDICO FOREIGN KEY (id_medico) REFERENCES MEDICOS(id) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENTE FOREIGN KEY (id_cliente) REFERENCES CLIENTS(id) ON DELETE CASCADE
);