CREATE TABLE MEDICOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(11) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    CONSTRAINT UK_EMAIL UNIQUE (email),
    CONSTRAINT UK_CPF UNIQUE (cpf)
);